### PR TITLE
Add elembuf.d

### PR DESCRIPTION
**Pull request by Cyroxin**
This is a quick and dirty version, which can be optimized further. You can also directly use the buffer instead of using my experimental version and setup your own synchronization, in which case you'd most likely get much better results.

### CODE REVIEW

**Comment by Cyroxin** [comment]
Here are some benchmarks on my windows machine. I was unable to get dlist to work due to a linking error, but the other comparisons worked fine!

````
Elembuf.d ldc $dub
received 1000000000 messages in 28237 msec sum=499999999500000000 speed=35414 msg/msec

mp.d ldc $dub
received 100000000 messages in 131731 msec sum=4999999950000000 speed=759 msg/msec

rwqueue.d ldc $dub
received 1000000000 messages in 185323 msec sum=499999999500000000 speed=5395 msg/msec

go.d ldc $dub
received 100000000 messages in 124417 msec sum=4999999950000000 speed=803 msg/msec
````

go.d did assert fail at line 40, but I assume that the version is old.

**Comment by mingwugmail** [comment]
What's the linking error message for dlist?

**Comment by mingwugmail** [comment]
> go.d did assert fail at line 40, but I assume that the version is old.

https://github.com/mingwugmail/liblfdsd/blob/master/comparison/go.d#L4

dependency "jin-go" version="~>2.0.0"

It is the latest version.

Can you print out the value when the assertion fails?

https://github.com/mingwugmail/liblfdsd/blob/master/comparison/go.d#L40

I think @nin-jin will look into it.

**Comment by mingwugmail** [comment]
@Cyroxin 

I wrapped a simple sync queue using elembuf here:

https://github.com/mingwugmail/liblfdsd/blob/master/comparison/elembuf_sync_queue.d#L25

(from https://tour.dlang.org/tour/en/multithreading/synchronization-sharing)

The result is about the same as plain D message passing between 2 threads:
https://github.com/mingwugmail/liblfdsd/blob/master/comparison/mp.d

```
$ make dmp
received 100000000 messages in 27574 msec sum=4999999950000000 speed=3626 msg/msec
$ make elembuf_sync_q
received 100000000 messages in 27078 msec sum=5000000050000000 speed=3693 msg/msec
```

I'm not sure if this is the best way to use elembuf, is elembuf internally thread-safe for 1-producer-1-consumer already? so no outside sync is needed?

The doc: https://cyroxin.github.io/Elembuf/buffer.html reads:
"Threaded | Create a background thread to fill the buffer. Makes it no longer directly castable to T[]."

What does it exactly mean to the producer thread?

Feel free to change my simple implementation to show-off elembuf's strength; or implement a (lock-free?/wait-free?) queue using elembuf.

Thanks.

**Comment by Cyroxin** [comment]
> @Cyroxin
> 
> I wrapped a simple sync queue using elembuf here:
> 
> https://github.com/mingwugmail/liblfdsd/blob/master/comparison/elembuf_sync_queue.d#L25
> 
> (from https://tour.dlang.org/tour/en/multithreading/synchronization-sharing)
> 
> The result is about the same as plain D message passing between 2 threads:
> https://github.com/mingwugmail/liblfdsd/blob/master/comparison/mp.d
> 
Heya,

You shouldn't use sync as it is very inefficient. If I understood sync correctly, it wraps anything inside with a mutex. You also seem to have some odd issue with your code as your sum is incorrect. I checked if it works better on linux, so I used my ubuntu for benchmarking. 

````
elembufsync ldc ubuntu
received 100000000 messages in 142980 msec sum=5000000050000000 speed=699 msg/msec

rwqueue ldc ubuntu
received 1000000000 messages in 180066 msec sum=499999999500000000 speed=5553 msg/msec
````
By comparison to elembuf experimental:
````
elembufthreaded ldc ubuntu
received 1000000000 messages in 28083 msec sum=499999999500000000 speed=35608 msg/msec
````

The threaded experimental version of elembuf creates a thread from the threadpool, which is much better than doing it directly. It also uses only atomics for accessing variables and never accesses the consumers variables so that it could be made thread local by the compiler, which is huge from a performance standpoint. The main thread is the consumer/command thread, which on every fill reads a msg from a mailbox from the background thread containing count of items that have been filled and responds back with an order for more items. The consumer can also order thread termination from that same mailbox.

> 
> I'm not sure if this is the best way to use elembuf, is elembuf internally thread-safe for 1-producer-1-consumer already? so no outside sync is needed?
> The doc: https://cyroxin.github.io/Elembuf/buffer.html reads:
> "Threaded | Create a background thread to fill the buffer. Makes it no longer directly castable to T[]."
> 
> What does it exactly mean to the producer thread?
> 

The reason elembuf is castable directly to a T[] is that it actually is a T[]. However, when you add the "Threaded" experimental compile time option, a new shared mailbox variable is added for message passing, making the buffer larger than a T[]. The reason why I made a custom mailbox instead of using the phobos one is to save on variables. If you checked the Tid mailbox implementation, it has a lot of garbage that you don't necessarily need, at least I didn't need them all for this.

> Feel free to change my simple implementation to show-off elembuf's strength; or implement a (lock-free?/wait-free?) queue using elembuf.

I suggest you switch over to the experimental threaded buffer version using the compile time switch. It is wait free already. The https://www.liblfds.org/ -circular buffer/ring buffer uses many more variables than elembuf, which I do not personally suggest as setting variables does slow the speed down. One thing it has going for it is that it is passed by parameters, which I've been planning to implement with templates for the next major breaking change for the transition from 1.1.X -> 1.2.X. Passing by parameter is great in that I could mark all functions as pure and simplify the usage even further. I'm envisioning that instead of:
```` D
Buffer!() buf = Buffer!()();
buf << "Hello world!";
```` 
You'd have something like:

```` D
char[] buf = ring!"";
ring!buf.fill("Hello world!");
```` 

----

> dependency "jin-go" version="~>2.0.0"
>
> It is the latest version.
>
> Can you print out the value when the assertion fails?

No, I meant that the version of the compare file is old. The assert probably fails as the amount of times the go version has to run is less than what elembuf and others had to run. You have at least 3 zeroes less in it, which is most likely why the assert failed. You can see the sum in the above go run.

> What's the linking error message for dlist?

dub dlisttest.d
````
dlisttest.d(28,19): Error: undefined identifier AtomicDList
C:\Program Files\D\ldc2-1.21.0-windows-multilib\bin\ldc2.exe failed with exit code 1. 
````

"C:\Program Files\D\ldc2-1.21.0-windows-multilib\bin\ldc2.exe" dlist.d
````
lld-link: error: subsystem must be defined
````

**Comment by nin-jin** [comment]
> go.d did assert fail at line 40, but I assume that the version is old.

I just have added more memory barriers. Could you try version 2.0.1?

**Comment by Cyroxin** [comment]
> > go.d did assert fail at line 40, but I assume that the version is old.
> 
> I just have added more memory barriers. Could you try version 2.0.1?

2.0.1 was not in dub when I tested, so I used master instead.

<details>

````
#!/usr/bin/env dub
/+ dub.sdl:
name "app"
dependency "jin-go" version="~master"
+/

import std.datetime.stopwatch;
import std.stdio;

import jin.go;

const int n = 100_000_000;

void threadProducer(Output!int queue)
{
  foreach (int i; 0..n) {
	queue.put(i);
  }
}

void main()
{
	Input!int queue;
	jin.go.go.go!threadProducer(queue.pair);

	StopWatch sw;
	sw.start();
	long sum = 0;

	foreach (p; queue)
	{
		sum += p;
	}

	sw.stop();

	writefln("received %d messages in %d msec sum=%d speed=%d msg/msec", n,
			sw.peek.total!"msecs", sum, n / sw.peek.total!"msecs");
	
	assert(sum == (n * (n - 1) / 2));
}

````

````
received 100000000 messages in 163304 msec sum=4999999950000000 speed=612 msg/msec

core.exception.AssertError@go.d(40): Assertion failure
----------------
0x00007FF7269A2F8F in d_assert
0x00007FF7269212EE in go.D main at C:\Users\[redacted]\Desktop\test\go.d(40)
0x00007FF7269A78A9 in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll()
0x00007FF7269A7582 in d_run_main2
0x00007FF7269A7833 in d_wrun_main
0x00007FF7269311B7 in go.wmain at C:\Program Files\D\ldc2-1.21.0-windows-multilib\import\core\internal\entrypoint.d(32)
0x00007FF7269F7D4A in wmainCRTStartup
0x00007FF826EB7BD4 in BaseThreadInitThunk
0x00007FF827F6CE51 in RtlUserThreadStart
Program exited with code 1

````

</details>

**Comment by mingwugmail** [comment]
@Cyroxin 

> ... instead of "~=", use "<<" ...

Ah, can you overload opOpAssign "~" ?  It's an idiom in D to use "~=" to append to buffer. New users will definitely use "~=" by default.  This is more user friendly.

If there are special reasons that you do not want to overload "~=", then issue an compile-time *warning* message that the normal "~=" should be "<<=".

**Comment by mingwugmail** [comment]
@Cyroxin and

https://github.com/mingwugmail/liblfdsd/blob/master/comparison/elembuf_sync_queue.d#L28

        elements ~= value;
```
        elements <<= value;
```
elembuf_sync_queue.d(28,18): Error: none of the opOpAssign overloads of Buffer are callable for this.elements of type shared(Buffer!(int, false))

If I cast away shared:
```
        cast(Buffer!T)elements <<= value;
```
.dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(399,10): Error: static assert:  "Source interface not defined. See documentation for information. You may require a cast if doing [1,2,3] as an array."
.dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(575,14):        instantiated from here: fill!(true, int)

**Comment by mingwugmail** [comment]
@Cyroxin 

after I change to:
```
    alias BufferT = Buffer!(T, true);
    private BufferT elements;
...
    cast(BufferT)elements <<= value;
```
.dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(575,14): Error: template buffer.Buffer!(int, true).Buffer.fill cannot deduce function from argument types !(true)(int), candidates are:

**Comment by mingwugmail** [comment]
@Cyroxin  the way to  run Dlist is:

```
$ make dlist
ldc2 -O4 --release --boundscheck=off dlist_test.d dlist.d
./dlist_test
finished receiving1000000000
received 1000000000 messages in 42334 msec sum=0 speed=23621 msg/msec
```

**Comment by Cyroxin** [comment]
> @Cyroxin and
> 
> https://github.com/mingwugmail/liblfdsd/blob/master/comparison/elembuf_sync_queue.d#L28
> 
> ```
>         elements ~= value;
> ```
> 
> after change:
> 
> ```
>         elements <<= value;
> ```
> 
> elembuf_sync_queue.d(28,18): Error: none of the opOpAssign overloads of Buffer are callable for this.elements of type shared(Buffer!(int, false))
> 
> If I cast away shared:
> 
> ```
>         cast(Buffer!T)elements <<= value;
> ```
> 
> .dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(399,10): Error: static assert: "Source interface not defined. See documentation for information. You may require a cast if doing [1,2,3] as an array."
> .dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(575,14): instantiated from here: fill!(true, int)

You cannot fill buffers with objects, only arrays. This is made so that no one would fill items individually as that is very inefficient. If you really want to do it then you could turn T into a T[]. If you want to do it no matter what, then just increase length by one and add set the last index to the T.

Do note that if you are using the experimental threaded buffer, then you can never add items on your own. You must either give the background thread a new source or give it a non-null dummy source which does not fill and fill while the background thread is occupied by the dummy source.

I'm still suggesting that you use the experimental buffer as it is a 1 consumer 1 producer buffer. You could as well add another thread to work as the consumer thread if you do not want the main thread to be the consumer.

**Comment by Cyroxin** [comment]
> @Cyroxin
> 
> after I change to:
> 
> ```
>     alias BufferT = Buffer!(T, true);
>     private BufferT elements;
> ...
>     cast(BufferT)elements <<= value;
> ```
> 
> .dub/packages/elembuf-1.1.5/elembuf/source/buffer.d(575,14): Error: template buffer.Buffer!(int, true).Buffer.fill cannot deduce function from argument types !(true)(int), candidates are:

You're missing an exclamation mark on both. Not sure how you'd do it with an alias. I recommend just doing

```` D
Buffer!(T) elements = Buffer!(T)(); //Buffer!(T,false)
assert(typeof(values) == T[]);
elements <<= values;
````

**Comment by nin-jin** [comment]
Usage of `<<` operator for piping isn't d way. It's better to use `~=`:

```
    void opOpAssign(string op)(Message message) if (op == "~")
    {
        this.put(message);
    }
```

**Comment by Cyroxin** [comment]
> Usage of `<<` operator for piping isn't D-way. It's better to use `~=`:

That is true. It was originally added as two different versions were needed: optimized (<<=) and unoptimized (<<). I'll need to look into how I would create overrides for them both with concat. However, you can always not use it at all and directly call the fill function. I've edited the unthreaded version example to show alternatives for both.

**Comment by nin-jin** [comment]
Why do you need an unoptimized version?

**Comment by Cyroxin** [comment]
> Why do you need an unoptimized version?

😄 
The restrictions are quite strict in the optimized version. While it is called "unoptimized version", it is actually far from the truth. The difference is just one & -bitoperation. 

To take advantage of the optimized version, you would have to know how many pops you have done at compile time or at least approximate it to be less than what is the buffer's max. At some point you still need to do an unoptimized fill regardless. It is just useful for those who necessarily need more data and wish to postpone the buffer "overhead", which is one & -binary operation. Some may say that optimizing away a simple binary operation is too far, which in all honesty is absolutely correct. I still prefer it though as benchmarks such as this, which compare single item fills rather than array or IO fills tend to gain substantially from having just one & -binary operation instead of 4096.

**Pull request merged**
